name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    #   - name: Install dependencies
    #     run: npm i
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_username: ${{ secrets.USERNAME }}
          CYPRESS_password: ${{ secrets.PASSWORD }}
          CYPRESS_address: ${{ secrets.ADDRESS }}
          CYPRESS_locationName: ${{ secrets.LOCATIONNAME }}
          CYPRESS_formattedAddress: ${{ secrets.FORMATTEDADDRESS }}